[package]
name = "template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.3"
itertools = "0.12.1"
petgraph = "0.6.3"
ac-library-rs = "0.1.1"